fix: 为 InstallConfirmActivity 添加 AppCompat 主题
## 问题
`InstallConfirmActivity` 使用 `AlertDialog.Builder` 时需要 `Theme.AppCompat` 主题，否则会导致崩溃：
```
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
```

## 解决方案
在 `AndroidManifest.xml` 中为 `InstallConfirmActivity` 指定 `Theme.AppCompat.Light.Dialog.Alert` 主题。

## 修改内容
- app/src/main/AndroidManifest.xml: 为 `InstallConfirmActivity` 添加 `android:theme="@style/Theme.AppCompat.Light.Dialog.Alert"`

Fixes #799329974874